# Generated by Django 3.1.6 on 2021-02-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='inn',
            field=models.CharField(max_length=12, unique=True, verbose_name='TIN'),
        ),
    ]
