# Generated by Django 3.1.6 on 2021-02-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20210218_2336'),
    ]

    operations = [
        migrations.RenameField(
            'CustomUser', 'inn', 'tin'),
    ]
